# Generated by Django 3.1.5 on 2021-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210130_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_article',
            field=models.BooleanField(default=False),
        ),
    ]
