# Generated by Django 3.1.5 on 2021-01-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_sub_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sub_article',
        ),
    ]
