# Generated by Django 3.1.5 on 2021-02-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210131_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=99)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
