# Generated by Django 3.1.5 on 2021-02-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
