# Generated by Django 3.1.5 on 2021-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published'), ('Pending', 'pending'), ('Returned', 'returned')], max_length=177),
        ),
    ]
