# Generated by Django 3.1.5 on 2021-02-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_translatemodel_translatemodeltranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='translatemodeltranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='translatemodeltranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='TranslateModel',
        ),
        migrations.DeleteModel(
            name='TranslateModelTranslation',
        ),
        migrations.AddField(
            model_name='article',
            name='visit_count',
            field=models.ManyToManyField(blank=True, related_name='visit_count', to='core.IPAddress'),
        ),
    ]
