# Generated by Django 3.1.5 on 2021-02-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210203_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='visit_count',
        ),
        migrations.DeleteModel(
            name='ArticleVisit',
        ),
    ]
