# Generated by Django 3.1.5 on 2021-02-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210203_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='visit_count',
            field=models.ManyToManyField(blank=True, related_name='visit_count', through='core.ArticleVisit', to='core.IPAddress'),
        ),
    ]
